# permissions for end users to edit aoms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: aom-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: aom
    app.kubernetes.io/part-of: aom
    app.kubernetes.io/managed-by: kustomize
  name: aom-editor-role
rules:
- apiGroups:
  - automation.buaa.io
  resources:
  - aoms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - automation.buaa.io
  resources:
  - aoms/status
  verbs:
  - get
