apiVersion: automation.buaa.io/v1
kind: AOM
metadata:
  labels:
    app.kubernetes.io/name: aom
    app.kubernetes.io/instance: aom-sample
    app.kubernetes.io/part-of: aom
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: aom
  name: aom-sample
spec:
  collector:
    address: http://192.168.49.2/prometheus
    scrapeInterval: 15
  interval: 30
  metrics:
    entitiy1:
      name: http_request_01
      query: sum(delta(http_requests_total[30s]))
      scaleDownConf:
        duration: 500
        threshold: "100"
      target: "50"
      unit: num
      weight: 100
  models:
    entitiy1:
      - attr:
          slen : "12"
          look_forward : "24"
          look_backward : "60"
          alpha : "0.716"
          beta : "0.029"
          gamma : "0.993"
        needTrain: false
        type: holt_winter
  scaleTargetRef :
      kind : Deployment
      name: my-app-deployment
      apiVersion: apps/v1



